"""07_Adicionado_usuarios_e_relacionamentos

Revision ID: 5db7322b3896
Revises: 9cf7a7cbe507
Create Date: 2022-02-28 21:14:18.774248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7322b3896'
down_revision = '9cf7a7cbe507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
