"""Inicial

Revision ID: 64709250e205
Revises: 
Create Date: 2022-02-28 18:33:12.438765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64709250e205'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
