"""finalizado

Revision ID: 660e357f68c6
Revises: 671dee8ea9ea
Create Date: 2022-03-07 03:30:28.549547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660e357f68c6'
down_revision = '671dee8ea9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
