"""08_Adicionado_pedidos

Revision ID: 671dee8ea9ea
Revises: 5db7322b3896
Create Date: 2022-03-04 23:52:15.754228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671dee8ea9ea'
down_revision = '5db7322b3896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('local_de_entrega', sa.String(), nullable=True),
    sa.Column('entrega_ou_retirada', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name='fk_pedido_produto'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_pedido_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
