"""Tamanhos removidos

Revision ID: 73b72eeac8fb
Revises: be076c2ac287
Create Date: 2022-02-28 18:51:39.771966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b72eeac8fb'
down_revision = 'be076c2ac287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'tamanhos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('tamanhos', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
