"""Tamanhos

Revision ID: be076c2ac287
Revises: ffb0758beefb
Create Date: 2022-02-28 18:50:31.196572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be076c2ac287'
down_revision = 'ffb0758beefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
